# Generated by Django 4.2.16 on 2024-09-14 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=30, unique=True, verbose_name='art')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('category', models.CharField(choices=[('modul_single', 'modul_single'), ('modul_left', 'modul_left'), ('modul_right', 'modul_right'), ('modul_center', 'modul_center'), ('modul_22_left', 'modul_22_left'), ('modul_22_right', 'modul_22_right'), ('modul_22_center', 'modul_22_center'), ('modul_angle_90', 'modul_angle_90'), ('screen_single_45', 'screen_single_45'), ('screen_single_85', 'screen_single_85'), ('screen_left_45', 'screen_left_45'), ('screen_left_85', 'screen_left_85'), ('screen_right_45', 'screen_right_45'), ('screen_right_85', 'screen_right_85'), ('screen_center_45', 'screen_center_45'), ('screen_center_85', 'screen_center_85'), ('screen_angle_90_45', 'screen_angle_90_45'), ('screen_angle_90_85', 'screen_angle_90_85'), ('screen_22_center_45', 'screen_22_center_45'), ('screen_22_center_85', 'screen_22_center_85'), ('screen_22_left_45', 'screen_22_left_45'), ('screen_22_left_85', 'screen_22_left_85'), ('screen_22_right_45', 'screen_22_right_45'), ('screen_22_right_85', 'screen_22_right_85'), ('schine_montage', 'schine_montage'), ('option', 'option')], max_length=100, verbose_name='category')),
                ('url_image', models.URLField(blank=True, verbose_name='url_image')),
                ('lens', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='lens')),
            ],
        ),
    ]
