# Generated by Django 4.2.16 on 2024-09-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='value_for_select',
            field=models.CharField(default='t', max_length=200, verbose_name='value_for_select'),
            preserve_default=False,
        ),
    ]
